### ISSUE TITLE
Creating monitoring regions without major and minor

### ISSUE THREAD

**Issue by codingjam** [inthepocket/ibeacon-scanner-android#9]
Hi,

I am trying to use this library in my project and I have a couple of questions.

- Is there a way to create a Monitoring region without specifying Major and Minor, and only create regions based on UUID? If that is possible, how can we know which exact beacon (UUID+Maj+Minor) triggered the didEnter/Exit event?
- Can we create multiple Monitoring regions?

Appreciate your help!

**Comment by eliaslecomte** [comment]
Hi codingjam,

Regarding monitoring multiple beacons, you can monitor as many beacons you want, by calling `IBeaconScanner.getInstance().startMonitoring(beacon);` for every iBeacon you want to monitor.

Small sidenote: `void didEnterBeacon(Beacon beacon);` always passes a newly created Beacon object, with the UUID, major and minor seen by the BLE layer.

To explain shortly about Regions, Region monitoring is typically when you monitor for a specific UUID, and receive all Beacons with that UUID, but varying major and minor. This library concentrates on iBeacon monitoring, so by default you specify both UUID, major and minor.

At current, we have not included the possibility to monitor a Region. Until we would add this, do you have the possibility to include the entire library in your product or work on this library? You would only have to modify line 61 & 64 of [ScanFilterUtils](https://github.com/inthepocket/ibeacon-scanner-android/blob/develop/ibeaconscanner/src/main/java/mobi/inthepocket/android/beacons/ibeaconscanner/utils/ScanFilterUtils.java).

Those mask bytes indicate that the major and minor have to match the ones specified in the Beacon object. By changing them from 11 / 11 to 00 / 00, it will return any Beacon with the correct UUID and pass the major and minor values seen.

Then you would only have to call `IBeaconScanner.getInstance().startMonitoring(beacon);` once for every UUID you want to monitor (you can use any number for major and minor as it will not care about the ones you specified).

Do you have any further question and this and what will you to?

**Comment by codingjam** [comment]
Thanks for your detailed response, that was very helpful. I am creating a cordova plugin that will run as Android service and monitor for beacons after the app is killed. It would be perfect if I can make the suggested changes and generate a jar file that I can just include with background service plugin. What would be the best way to to do it?

**Comment by eliaslecomte** [comment]
Hi,

If you want to develop fast, the best way would be if you change the code so that you can generate your jar. If the code is thoroughly tested and performs well we can later add it this library and publish it via jCenter.

I added a small wiki page on how to contribute to this library: https://github.com/inthepocket/ibeacon-scanner-android/wiki/Contributing-to-iBeacon-Scanner-Android

So what you could do is:
1. Fork the code base from the develop branch: https://github.com/inthepocket/ibeacon-scanner-android/tree/develop
2. Create a feature branch feature/region_scanning
3. Implement the changes, generate your jar by running the project

I think it would be nice if there were both `Beacon` and `Region` objects. A Region object would be created the following way:

``` java
final Region region = Region.newBuilder()
    .setUUID("84be19d4-797d-11e5-8bcf-feff819cdc9f")
    .build();
```

And then you could pass:

`IBeaconScanner.getInstance().startMonitoring(region);`

IBeaconScanner would have to be changed to accommodate both `Region`s and `Beacon`s and create the correct ScanFilter for each of them. So `ScanFilterUtils` would need some changing as well.

I'll discuss with our solution architect if he thinks that one library for both Beacon and Region scanning is a good idea. Maybe it's better that there is a forked library that can only do Region scanning.

**Comment by codingjam** [comment]
Thanks @eliaslecomte I was able to make the changes you suggested locally and generate a AAR file. Included that with my plugin and its working fine. I don't have time to make changes and commit to the library right now, but will reach out to you for sure if I can spare some time. Appreciate your help.

**Comment by codingjam** [comment]
@eliaslecomte just wanted to let you know about something I noticed. After changing the mask from 1/1 to 0/0 in ScanFilterUtils class it is firing enter/exit events for UUIDs that are not matching in some cases. I changed only the last character of the uuid, it still triggers the monitoring events for that beacon even when I am not monitoring for it, but if I completely change the uuid to a new value it works fine.

**Comment by eliaslecomte** [comment]
Hard to tell what's going wrong @codingjam. You are scanning for `84be19d4-797d-11e5-8bcf-feff819cdc9y` but get `84be19d4-797d-11e5-8bcf-feff819cdc9f`?

Would help if you fork this library and push your code changes to github.
Are you also seeing this when you use [iBeacon Scanner Android](https://github.com/inthepocket/ibeacon-scanner-android) without your modifications?
